[package]
name = "untitled"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
eframe = { version = "0.29.1", default-features = false, features = ["default_fonts", "glow", "persistence"] }
egui = "0.29.1"
rfd = "0.15.1"
